### ISSUE TITLE
I use this model in the task -- English translate to Chinese, the result is very bad.

### ISSUE THREAD

**Issue by pengwei-iie** [yuanxiaosc/Seq2Seq-English-French-Machine-Translation-Model#1]
I do not know why.

**Comment by yuanxiaosc** [comment]
> I do not know why.

Because this seq2seq model only uses the end state of the encoder to initialize the state of the decoder, it does not use more information. You can use my another code [Keras_Attention_Seq2Seq](https://github.com/yuanxiaosc/Keras_Attention_Seq2Seq) .
